version: '3.6'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /server
    volumes: 
     - .:/server
    ports:
      - 3001:3001
    depends_on:
      - db
    restart: always
    entrypoint: go run main.go

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
